### ISSUE TITLE
[Enhancement] Keyboard support

### ISSUE THREAD

**Issue by cbwang2016** [SMerrony/tello-desktop#3]
Honestly, I think your code is better than mine. So I really hope you can add this feature, for I have no gamepad.

**Comment by SMerrony** [comment]
I've put very basic keyboard control into my app.

Unfortunately the Gobot support for keyboard is very primitive.  I think I should look at moving to SDL for it, but that requires a whole new set of event handling etc. and I can't find a good example to crib!

**Comment by SMerrony** [comment]
OK - changed to SDL keyboard handling which is a bit more polished than Gobot's.

I've flown with it a few times and it's working OK albeit rather conservatively w.r.t. speeds etc.  I'll add repeat keypress handling soon so that speed can be controlled.  

Remember, most actions continue until the spacebar is hit!
